### ISSUE TITLE
Error: Cannot find module 'azure-arm-apimanagement'

### ISSUE THREAD

**Issue by Vineet-Sharma29** [cloudlibz/nodecloud-web#32]
I am trying to run `server`. However, I am getting following error:-

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'azure-arm-apimanagement'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/vineet/osp/nodecloud-azure-plugin/utilities/azure-api.js:1:91)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/vineet/osp/nodecloud-azure-plugin/index.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

Unable to figure out how to install `azure-arm-apimanagement` module.

**Comment by amrita019** [comment]
Hello @Vineet-Sharma29 
nodecloud-azure-plugin is currently manually added to the project.
Please refer to https://github.com/cloudlibz/nodecloud-web/issues/21 for fixing it for now.
